"""empty message

Revision ID: 5dc5bec7c9fb
Revises: 9acd6f464689
Create Date: 2018-11-13 18:17:31.989352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dc5bec7c9fb'
down_revision = '9acd6f464689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_author_fkey', 'post', type_='foreignkey')
    op.drop_column('post', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('post_author_fkey', 'post', 'user', ['author'], ['id'])
    # ### end Alembic commands ###
