"""empty message

Revision ID: 7923d8902f1e
Revises: 6f88bd07c5cc
Create Date: 2018-11-22 19:15:28.676075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7923d8902f1e'
down_revision = '6f88bd07c5cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('abs', sa.String(length=20), server_default='abc', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'abs')
    # ### end Alembic commands ###
