"""empty message

Revision ID: 9acd6f464689
Revises: 8f9e65429680
Create Date: 2018-11-13 18:16:18.048946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9acd6f464689'
down_revision = '8f9e65429680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'downvotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('downvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
