"""empty message

Revision ID: aa4e96877385
Revises: 7923d8902f1e
Create Date: 2018-11-22 19:19:53.857337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa4e96877385'
down_revision = '7923d8902f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cnf', sa.Boolean(), nullable=True))
    op.drop_column('user', 'abs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('abs', sa.VARCHAR(length=20), server_default=sa.text("'abc'::character varying"), autoincrement=False, nullable=True))
    op.drop_column('user', 'cnf')
    # ### end Alembic commands ###
